# Generated by Django 5.1.4 on 2025-01-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Testing Courses',
            },
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Software Courses'},
        ),
    ]
