# Generated by Django 5.1.4 on 2025-01-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testing_courses_alter_courses_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='networking_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Networking Courses',
            },
        ),
    ]
