# Generated by Django 5.1.4 on 2025-01-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_other_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_details_name',
            field=models.CharField(default='CourseX', max_length=50),
        ),
        migrations.AddField(
            model_name='networking_courses',
            name='course_details_name',
            field=models.CharField(default='CourseX', max_length=50),
        ),
        migrations.AddField(
            model_name='other_courses',
            name='course_details_name',
            field=models.CharField(default='CourseX', max_length=50),
        ),
        migrations.AddField(
            model_name='testing_courses',
            name='course_details_name',
            field=models.CharField(default='CourseX', max_length=50),
        ),
    ]
