# Generated by Django 5.1.4 on 2025-01-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_courses_course_details_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(default='4 months course + 3 months on the Job Training', max_length=50),
        ),
        migrations.AddField(
            model_name='networking_courses',
            name='course_duration',
            field=models.CharField(default='4 months course + 3 months on the Job Training', max_length=50),
        ),
        migrations.AddField(
            model_name='other_courses',
            name='course_duration',
            field=models.CharField(default='4 months course + 3 months on the Job Training', max_length=50),
        ),
        migrations.AddField(
            model_name='testing_courses',
            name='course_duration',
            field=models.CharField(default='4 months course + 3 months on the Job Training', max_length=50),
        ),
    ]
