# Generated by Django 5.1.4 on 2025-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_courses_course_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='networking_courses',
            name='networking_contents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='other_courses',
            name='other_contents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testing_courses',
            name='testing_contents',
            field=models.TextField(blank=True),
        ),
    ]
