# Generated by Django 5.1.4 on 2025-01-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_networking_courses_networking_contents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.DeleteModel(
            name='networking_courses',
        ),
        migrations.DeleteModel(
            name='other_courses',
        ),
        migrations.DeleteModel(
            name='testing_courses',
        ),
    ]
