# Generated by Django 5.1.4 on 2025-01-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0009_delete_courses_delete_networking_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courses_name', models.TextField()),
                ('parent_id', models.IntegerField(default=1)),
                ('details_name', models.TextField()),
            ],
        ),
    ]
