# Generated by Django 5.1.4 on 2025-01-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_courses_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='parent_id',
            field=models.IntegerField(),
        ),
    ]
