# Generated by Django 5.1.4 on 2025-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_courses_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.TextField(default='4 months course + 3 months on the Job Training'),
        ),
    ]
