# Generated by Django 5.1.4 on 2025-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('guardian_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('mode', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_timings', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
