# Generated by Django 5.1.4 on 2025-02-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
