# Generated by Django 5.1.4 on 2025-02-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_students_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='additional_courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
